name: ci

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 19 with enhanced caching
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 19
          cache: maven
          cache-dependency-path: '**/pom.xml'

      # 3. Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 4. Setup Chrome for headless testing
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      # 5. Install Allure CLI
      - name: Install Allure CLI
        run: |
          echo "Installing Allure CLI..."
          curl -o allure-2.30.0.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.30.0/allure-commandline-2.30.0.tgz
          sudo tar -zxvf allure-2.30.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.30.0/bin/allure /usr/bin/allure
          echo "Allure version:"
          allure --version

      # 6. Validate test environment
      - name: Validate Environment
        run: |
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn -version
          echo "Allure version:"
          allure --version

      # 7. Clean old directories and run tests
      - name: Clean and run tests
        run: |
          rm -rf target/allure-results target/allure-report || true
          echo "Starting test execution..."
          mvn clean test -Dtest=**/ci/*Test
        env:
          HEADLESS: true

      # 8. Generate Allure HTML report
      - name: Generate Allure Report
        if: always()
        run: |
          echo "Checking for test results..."
          if [ -d "target/allure-results" ] && [ "$(ls -A target/allure-results)" ]; then
            echo "Allure results found, generating report..."
            ls -la target/allure-results/
            allure generate target/allure-results --clean -o target/allure-report
            echo "Report generated successfully"
            ls -la target/allure-report/
          else
            echo "No allure-results found or directory is empty"
            echo "Creating empty report structure..."
            mkdir -p target/allure-report
            echo "<html><body><h1>No test results found</h1><p>The test execution did not generate Allure results.</p></body></html>" > target/allure-report/index.html
          fi

      # 9. Upload Allure Report for Pages deployment
      - name: Upload Allure Report for Pages
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-pages
          path: target/allure-report/
          retention-days: 1

      # 10. Upload Test Results Summary
      # - name: Upload Test Results Summary
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results-${{ github.run_number }}
      #     path: |
      #       target/surefire-reports/
      #       target/allure-results/
      #     retention-days: 7

  # Separate job for GitHub Pages deployment
  deploy-pages:
    needs: test
    if: always() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Download the Allure report
      - name: Download Allure Report
        uses: actions/download-artifact@v4
        with:
          name: allure-report-pages
          path: ./allure-report

      # 2. Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 3. Upload to GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # 5. Print deployment URL (instead of commenting)
      - name: Print deployment URL
        if: steps.deployment.outputs.page_url
        run: |
          echo "🚀 Allure Report deployed successfully!"
          echo "📊 View the report at: ${{ steps.deployment.outputs.page_url }}"